Repository ANSHIKA-26/WordWise, pull requests merged in 2024-11, with the labels that each got.

#1593 Added backend api for contanct us with proper folder structure
  backend/app.js
  backend/controllers/contactController.js
  backend/models/contact.js
  backend/routes/contactRoute.js
  frontend/src/pages/Contact.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1595 Change shadow effect on card
  .vscode/settings.json
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1597 fixed css of heart and comment icon on home page
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1601 backend api of feedback form
  backend/app.js
  backend/controllers/feedController.js
  backend/controllers/feedbackcontroller.js
  backend/models/feedback.js
  backend/routes/feebackroute.js
  backend/routes/feedbackRoute.js
  frontend/src/pages/Feedback.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1608 Added backend for get in touch form
  backend/app.js
  backend/controllers/getInTouchController.js
  backend/models/getInTouch.js
  backend/routes/getInTouchRoutes.js
  frontend/src/pages/About.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1615 Added backend for add blog page also render the blog data on blogPage
  backend/app.js
  backend/controllers/addBlogController.js
  backend/models/addBlog.js
  backend/package-lock.json
  backend/routes/addBlogRoutes.js
  frontend/src/pages/AddBlog.js
  frontend/src/pages/Blogs.js
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#1611 Implemented website visitor count dynamically
  blog.html
  category.html
  contact.html
  index.html
  privacy.html
  script.js
  start_writing.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1617 Fully Functional login with google and signup with google button options
  index.html
  login.html
  signup.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1619 Improve Card Design in Category Section
  category.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1625 Added feature to post the blog from draft also filter the blog accord…
  backend/controllers/addBlogController.js
  frontend/src/pages/BloggerProfile.js
  frontend/src/pages/Blogs.js
  frontend/src/styles/output.css
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#1624 Add a User Profiles page done ! #1599
  index.html
  profile.html
  style.css
  testp.css
  testp.js
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#1640 Added Sticky Header to Privacy Policy Page for Enhanced Accessibility
  privacy.html
Labels: gssoc-ext, hacktoberfest-accepted

#1639 added back to top button
  blog.html
  bookmarks.html
  category.html
  chatbot.html
  comment1.html
  comment10.html
  comment11.html
  comment12.html
  comment13.html
  comment14.html
  comment2.html
  comment3.html
  comment4.html
  comment5.html
  comment6.html
  comment7.html
  comment8.html
  comment9.html
  contact.html
  contact_us.html
  fashion.html
  food.html
  gaming_chronicles.html
  give_feedback.html
  health.html
  index.html
  life.html
  privacy.html
  resetpass.html
  start.html
  start_writing.html
  tech.html
  travel.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1641 done with footer changes#1587
  blog.html
  category.html
  contact_us.css
  contact_us.html
  give_feedback.html
  index.html
  start_writing.css
  start_writing.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1642 Optimized website load time
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1654 Added animation on scroll on full website
  frontend/src/components/Footer.js
  frontend/src/components/Navbar.js
  frontend/src/index.html
  frontend/src/pages/About.js
  frontend/src/pages/AddBlog.js
  frontend/src/pages/BloggerProfile.js
  frontend/src/pages/Blogs.js
  frontend/src/pages/Categories.js
  frontend/src/pages/Contact.js
  frontend/src/pages/Feedback.js
  frontend/src/pages/Home.js
  frontend/src/pages/ReadMoreBlog.js
  frontend/src/styles/output.css
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#1659 Added google translator for full website
  frontend/src/components/Footer.js
  frontend/src/pages/GoogleTranslator.js
  frontend/src/styles/output.css
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#1650 Solved CORS Policy Blocking Access to FontAwesome Script issue.
  blog.html
  contact.html
  gaming_chronicles.html
  index.html
  privacy.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1663 fix the text visibility(Issue: #1648)
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1664 Added no blog found page
  frontend/src/pages/Blogs.js
  frontend/src/styles/output.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1676 Added toaster on all pages
  frontend/package.json
  frontend/src/main.js
  frontend/src/pages/About.js
  frontend/src/pages/AddBlog.js
  frontend/src/pages/Contact.js
  frontend/src/pages/Feedback.js
  frontend/src/styles/output.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1687 Added text to speak functionality
  frontend/src/pages/Blogs.js
  frontend/src/styles/output.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1688 Added a clean and clear terms of use page
  frontend/src/components/Footer.js
  frontend/src/pages/TermsOfUse.js
  frontend/src/styles/output.css
  frontend/src/utils/router.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1691 Added social media sharing icon
  frontend/src/pages/Blogs.js
  frontend/src/styles/output.css
  frontend/src/utils/router.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1682 fixed alignment of icons in footer
  blog.html
  contact_us.css
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1686 Added "remember me" to the signup and signin page connecting it to the local storage database for user authentication.
  frontend/src/pages/Login.js
  index.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1713 Fix 404 Page Redirection for Invalid Routes
  .htaccess
  404.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1714 Maked profile page responsive and also fixes some issues in login page
  frontend/src/pages/BloggerProfile.js
  frontend/src/pages/Login.js
  frontend/src/styles/output.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1698 Added js for profile icon, login, signup and hamburger menu in responsive mode
  bookmarks.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1731 Added subscribe us feature on newsletter
  backend/app.js
  backend/controllers/subscribeController.js
  backend/models/subscribe.js
  backend/routes/subscribeRoutes.js
  backend/utils/sendMailToSubscribe.js
  frontend/src/components/Footer.js
  frontend/src/styles/output.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1730 made profile section responsive
  profile.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1723 send the user feedback data to admin on mail
  backend/.env.example
  backend/controllers/feedController.js
  backend/sendFeedbackToAdmin.js
  frontend/src/pages/Feedback.js
  frontend/src/styles/output.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1715 Maked hamburger working on smaller screen
  frontend/src/components/Navbar.js
  frontend/src/styles/navbar.css
  frontend/src/styles/output.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1727 fixed scroll btn
  contact_us.html
  give_feedback.html
  index.html
  start_writing.css
  start_writing.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1739 Editing Of profile is working now with the help of JavaScript
  index.html
  profile.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1722 Add Edit Profile Feature in Profile Page done🟢
  index.html
  profile.html
  profileedit.html
  testp.js
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#1742 added profile section on rest of the pages
  blog.html
  category.html
  contact_us.html
  give_feedback.html
  index.html
  start_writing.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1749 Add PWA (Progressive Web App) done !
  icon-192x192.png
  icon-512x512.png
  index.html
  manifest.json
  scripts.js
  sw.js
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#1755 Added Contact Form Mobile Number Validation
  contact_us.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1756 Update mismatch footer in category section
  comment1.html
  comment10.html
  comment11.html
  comment12.html
  comment13.html
  comment14.html
  comment2.html
  comment3.html
  comment4.html
  comment5.html
  comment6.html
  comment7.html
  comment8.html
  comment9.html
  contact.html
  fashion.html
  food.html
  health.html
  life.html
  style.css
  tech.html
  travel.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1752 Added Ai supported title generator
  backend/.env.example
  backend/generateTrendingTitles.py
  backend/package-lock.json
  frontend/src/pages/Home.js
  frontend/src/styles/output.css
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#1757 Category section -> image changes
  category.html
  fashion.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1762 contact_us updated
  contact_us.js
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1766 Added AI generated content feature ✨
  backend/generateFromAi.py
  backend/generateTrendingTitles.py
  frontend/src/pages/AddBlog.js
  frontend/src/styles/output.css
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#1711 Removed Profile Bugs
  SignIn_SignUp.js
  index.html
  main.js
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#1782 Interactive Discussion Forum with CURD operation & Responsive Design
  frontend/src/components/Navbar.js
  frontend/src/pages/DiscussionForum.js
  frontend/src/styles/output.css
  frontend/src/utils/router.js
  index.html
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#1785 SMOOTH SCROLLERBAR
  blog.html
  bookmarks.html
  category.html
  chatbot.html
  fashion.html
  frontend/src/index.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1783 GIVES SUITABLE COLORS
  blog.html
Labels: gssoc-ext, hacktoberfest-accepted

#1793 Added backend api for both answered and unanswered question
  backend/app.js
  backend/controllers/discussionController.js
  backend/models/discussion.js
  backend/routes/discussionRoutes.js
  frontend/src/pages/DiscussionForum.js
  frontend/src/styles/output.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1791 added newsleeter api and template
  backend/controllers/contactController.js
  backend/routes/contactRoute.js
  index.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1798 Added backend for forum
  backend/app.js
  backend/controllers/faqController.js
  backend/models/answers.js
  backend/models/question.js
  backend/routes/faqRoutes.js
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#1800 Fixed Save and Cancel Button UI
  profile.html
  testp.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1807 Update index.html and style.css
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1801 Added Password Change Modal
  profile.html
  testp.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1787 Issue number #1780 and #1781 is solved
  blog.html
  category.html
  contact_us.css
  contact_us.html
  give_feedback.html
  index.html
  start_writing.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1803 Changed the scrollup button
  blog.html
  bookmarks.html
  category.html
  comment1.html
  comment10.html
  comment11.html
  comment12.html
  comment13.html
  comment14.html
  comment2.html
  comment3.html
  comment4.html
  comment5.html
  comment6.html
  comment7.html
  comment8.html
  comment9.html
  contact.html
  contact_us.html
  fashion.html
  food.html
  gaming_chronicles.html
  give_feedback.html
  health.html
  life.html
  privacy.html
  start.html
  start_writing.html
  tech.html
  travel.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1812 fixed social media icons and unalign icons
  index.html
  start_writing.css
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1813 "✨ Dynamic Category and Tags Integration Using AI ✨"
  backend/generateFromAi.py
  backend/models/addBlog.js
  frontend/src/pages/AddBlog.js
  frontend/src/styles/output.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1819 Proper Profile Page (Dynamic)
  profile.html
  profile.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1818 done with the changes #1644 and #1646
  blog.css
  blog.html
  category.html
  contact_us.html
  give_feedback.html
  index.html
  start_writing.html
  start_writing.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1821 fixes #1809 [color of word of the day and sentences]
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1823 linked blog.html
  index.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1825 Added Debouncing Effect to SignUp page
  index.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1827 Fixes issue #1814 [Add icons on contact us page.]
  contact_us.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1829 ✨ Builded a Stories Page: Enable Bloggers to Create and View stories / experience of other blogger !!✨🔥
  frontend/src/pages/Stories.js
  frontend/src/styles/output.css
  frontend/src/utils/router.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1831 Build Backend for Stories Page: Implement CURD operation Routes ✨🚀
  backend/app.js
  backend/controllers/postsController.js
  backend/models/postModel.js
  backend/routes/storiesRoutes.js
  frontend/src/components/Footer.js
  frontend/src/pages/Stories.js
  frontend/src/styles/output.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1817 updating scroll button in main page
  index.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1835 Back to Top Button Disappears on Start Writing Tab During Scroll
  start_writing.css
  start_writing.js
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1836 added uniform footer to my reading list page
  bookmarks.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted
