Repository ANSHIKA-26/WordWise, pull requests merged in 2024-10, with the labels that each got.

#5 Fix text color blending issue in blog post section
  style.css
Labels: ggsoc-ext, level 1

#44 changed redirection of logo
  blog.html
  category.html
  index.html
  start.html
Labels: ggsoc-ext, level 1

#53 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: ggsoc-ext, level 1

#67 Fixted Footer background color and text for better visibility issue #3
  style.css
Labels: level 1

#83 darkMode toggle created!
  blog.html
  category.html
  darkMode.js
  index.html
  start.html
  style.css
Labels: ggsoc-ext, level 2

#90 Added Active Navbar Feature with Enhanced Color Scheme : Issue no #51
  blog.html
  category.html
  index.html
  main.js
  start.html
  style.css
Labels: ggsoc-ext, level 2

#101 Color fixed
  .vscode/settings.json
  darkMode.js
  style.css
Labels: ggsoc-ext, level 1

#114 Improved About Us and Contact Us sections with new features and UI up…
  about.html
  blog.html
  category.html
  contact.html
  index.html
  start.html
Labels: ggsoc-ext, level 2

#24 Navbar and Image Update with 3D Effect
  README.md
  Screenshot (267).png
  index.html
  style.css
Labels: ggsoc-ext

#119 Align Cards on Homepage for Improved Layout and Enhanced UI with Hover Effect : Issue no #55
  index.html
  start.html
  style.css
Labels: level 2

#124 Improve Hover Effect
  index.html
Labels: ggsoc-ext, level 1

#129 I have changed the footer and also changed the color palette to make it look more aesthetic. Issue #48
  index.html
  style.css
Labels: good first issue, level 1

#132 #33 navbar issue solved
  index.html
  style.css
Labels: ggsoc-ext, level 1, hacktoberfest-accepted

#140 Existing files links added to button
  index.html
Labels: ggsoc-ext, level 1, hacktoberfest-accepted

#137 redesign load more post
  index.html
Labels: ggsoc-ext, level 1, hacktoberfest, hacktoberfest-accepted

#151 Updated readme file
  README.md
Labels: ggsoc-ext, level 1

#146 enhanced the footer and dark theme also
  index.html
  style.css
Labels: level 1

#156 Made the footer text visible #126
  about.html
  blog.html
  category.html
  contact.html
  start.html
Labels: level 2

#147 Slider images
  index.html
  style.css
Labels: level 1

#149 Social media share feature
  index.html
  share.js
  style.css
Labels: level 1

#162 navbar background added
  category.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#165 Fixes #37 initialized npm package to setup the backend
  .gitignore
  package.json
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#167 hide scrollbar and fix navbar
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#174 Navbar arrangements
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#179 Favicon fix
  images/android-chrome-192x192.png
  images/android-chrome-512x512.png
  images/apple-touch-icon.png
  images/favicon-16x16.png
  images/favicon-32x32.png
  images/favicon.ico
  images/site.webmanifest
  index.html
  package-lock.json
  site.webmanifest
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#183 [FIX] Landing page overflow-X fixed
  style.css
Labels: gssoc-ext, hacktoberfest-accepted

#198 updated nav bar section in index.html and css files---to enhance the nav bar and layout with equal alignment and for clear visibility of text in nav bar
  about.html
  index.html
  start.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#204 Solved Issue where image does not overlaps text.
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#211 updated NavBar
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#212 Added All Contributors' Profile Photos
  README.md
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#217 Update index.html for Twitter icon
  index.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#224 enhanced symmetry and size of photos
  index.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#225 Added separate contact us form with responsive design : Issue no #54
  contact_us.html
  start.html
Labels: gssoc-ext, hacktoberfest-accepted

#226 [FIX] Nav bar issue fixed
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted

#229 Revert "[FIX] Nav bar issue fixed"
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted

#208 Sharing Feature Added
  about.html
  share.js
Labels: enhancement, gssoc-ext, level 1, hacktoberfest-accepted

#230 dark mode and the Navbar feature working!
  about.html
  blog.html
  category.html
  contact.html
  darkMode.js
  index.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#233 All the pages fixed
  about.html
  blog.html
  category.html
  contact.html
  contact_us.css
  contact_us.html
  index.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#236 Email link
  about.html
  blog.html
  category.html
  contact.html
  index.html
  start.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#246 changed the image of the webite in readme file
  README.md
  images/website.png
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#252 Login and signup buttons working
  index.html
  main.js
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#253 [FIX] Nav Bar linkes and jumping fixed
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#270 deleted and arranged images in the repo
  README.md
  Screenshot (267).png
  Screenshot 2024-10-02 143221.png
  images/Untitled design.png
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#265 Newsletter added and Footer modified
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#276 Login validations completed Issue #243
  SignIn_SignUp.js
  index.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#281 Made the About in NavBar responsive
  about.html
  index.html
  main.js
  package-lock.json
  start.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#280 Improved the Navbar U.I.
  contact_us.css
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#282 SOLVED THE REDIRECTING ISSUE
  index.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#292 Integrated Email Sending Backend : Issue no #287
  backend/package-lock.json
  backend/package.json
  backend/server.js
  contact_us.html
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#301 Adding gaps in tags and social icons and change color and make structured
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#323 Categories redesign [Issue #283]
  assets/fashion.jpeg
  assets/health.jpeg
  category.css
  category.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#307 Backend created!✨(issue #256)
  SignIn_SignUp.js
  backend/login-Auth/login.js
  backend/signUp/signup.js
  blog.html
  category.html
  contact_us.css
  contact_us.html
  index.html
  start.html
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#335 In the footer section Feature Post section updated
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#342 made navbar consitent, start writing button visible in all pages
  about.html
  blog.html
  category.html
  contact_us.css
  contact_us.html
  index.html
  start.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#341 Add FAQ Section to the WordWise Website
  faq.js
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted

#357 Updated Favicon: issue #352
  about.html
  blog.html
  category.html
  contact.html
  contact_us.html
  images/favi.png
  images/favicon.jpg
  index.html
  start.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#363 display a popup message after submitting get in touch form and add message length validation
  contact_us.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#371 Cards hover effect added | #319
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#330 login/signup-ui-updated
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted

#377 In the Categories page Footer section updated
  category.html
  index.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#385 Home page Slider Picture override width of page issue is solved
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#393 [Enhancement Done]Enhanced FAQ UI #364
  faq.js
  index.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#395 Improved Load More Posts Button UI
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted

#403 improved date and icons
  index.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#407 Addition of Email Validation, Toast Alert PopUp, Newsletter Endpoint and Newsletter Service | Issue #289
  backend/newsLetter.js
  backend/server.js
  index.html
  style.css
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#394 updated toggle button ui
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted

#423 added hover effect to social icons
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#379 add website views widget #376
  index.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#436 Updated scrollbar styling for light and dark modes
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#470 Enhanced Submit Button fixes issue number #303
  blog.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted

#473 Improve Preloader
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#490 issue #414 Enhanced Signup Functionality with Validation and Password Visibility Toggle
  backend/signUp/signup.js
  index.html
  styles.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#494 removed svg logo
  about.html
  blog.html
  category.html
  contact_us.css
  contact_us.html
  darkMode.js
  index.html
  start_writing.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#503 Duplicate Button issue solved (Issue #489)
  blog.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#505 scroll bar and progress bar added
  Scroll_and_progressbar.css
  about.html
  blog.html
  category.css
  category.html
  contact_us.html
  index.html
  progress_bar.js
  start.html
  start_writing.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#507 Added the modified login & signup page under the profile icon
  about.html
  blog.html
  category.html
  contact_us.html
  images/profile.png
  index.html
  login.css
  login.html
  signup.css
  signup.html
  start_writing.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#509 Huge Gap above accordion__wrapper div reduced.
  style.css
Labels: gssoc-ext, hacktoberfest-accepted

#502 Enhanced the FAQ section in dark mode
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#508 Redesign of Leading Blog page
  blog.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#518 Fixed the Navbar Successfully !!
  index.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#527 fix footer ui improvemnt
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#545 Added Email functionality to the contact form issue #506
  backend/server.js
  contact_us.html
  contact_us.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#554 fix center alignment of button issue #530
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#556 Centering a Form and Button in the Middle of the Screen Using Flexbox
  index.html
  script.js
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#571 Newsletter Updation
  index.html
  script.js
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#590 added a simple and good pre loader
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#587 Api for blog post and Mongodb connection issue #546
  backend/Database.js
  backend/modal/BlogModal.js
  backend/package-lock.json
  backend/package.json
  backend/server.js
  start_writing.html
  start_writing.js
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#592 Fixing responsiveness issues.
  about.html
  blog.html
  category.css
  category.html
  contact_us.html
  index.html
  start_writing.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#616 Updated UI of the Contact Us Page
  contact_us.html
  login.html
  signup.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#614 Add password toggle functionality to both login and signup pages
  contact_us.html
  login.html
  signup.html
Labels: gssoc-ext, hacktoberfest-accepted

#594 Aditya UI
  index.html
  style.css
  styles.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#629 Improved card layout and styling in category page
  category.css
  category.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#628 passward show icon added
  about.html
  blog.html
  contact_us.html
  index.html
  start.html
  start_writing.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#619 Added Google Signin Frontend
  google_signin.js
  index.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#633 Google signin (button updated)
  assets/google_icon.jpg
Labels: gssoc-ext, hacktoberfest-accepted

#654 Modified the category card section with hover effects
  category.css
  category.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#668 Fixes#655:Login/signup page not properly aligned when opened
  index.html
Labels: gssoc-ext, hacktoberfest-accepted

#675 Fixed issue no.655 Login/signup page not properly aligned
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#669 Fixing_footer
  about.html
  blog.html
  category.html
  contact.html
  contact_us.html
  index.html
  start_writing.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#684 Forgot password modal added
  about.html
  blog.html
  category.html
  contact_us.html
  index.html
  main.js
  start.html
  start_writing.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#689 Enhanced the blog page ,Resolved #679
  blog.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#695 Bug fixed scroll to top button delay : Issue no #653
  index.html
Labels: gssoc-ext, hacktoberfest-accepted

#697 Fixes issue:#656:Icons in the Categories Page Bottom are not properly spaced and Twitter icon added
  category.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#692 Enhanced Navbar Design (Fixes #580)
  about.html
  blog.html
  category.html
  contact_us.css
  contact_us.html
  index.html
  profiledropdown.js
  start_writing.html
  style.css
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#722 NEW FEATURE : Like Button Added on the blog cards
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#678 Fix Chrome errors on home page
  backend/signUp/signup.js
  index.html
  main.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#737 Submit Button Fixed
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#759 Fixed Header color for Light mode issue ! #733
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#772 Enhanced the Login and Signup titles visibility in dark mode
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#773 Update logo to hyperlink to home page
  about.html
  blog.html
  category.html
  contact_us.html
  index.html
  start_writing.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#747 Added Feature Voice-to-Text Blogging and AI-Powered Writing Assistant
  Instructions.txt
  __pycache__/app.cpython-312.pyc
  app.py
  requirements.txt
  start_writing.css
  start_writing.html
  start_writing.js
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#774 Added password strength validation to signup page
  about.html
  blog.html
  category.html
  contact_us.html
  index.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#778 Improve comment form: Add floating labels, enhance button styling, in…
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#793 fixes #716 add cross button in all login signup forms.
  about.html
  blog.html
  category.html
  contact_us.html
  index.html
  login.html
  start_writing.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#795 Added all 6 Pages for categories
  category.css
  category.html
  fashion.html
  food.html
  health.html
  index.html
  life.html
  style.css
  tech.html
  travel.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#810 Fixes#783:The Send Button in both of the forms (Contact us and Feedback) is not hovering
  contact_us.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#799 Category Section Hover Effect Color Theme Issue
  category.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#811 Fixed icons color, message box, text color & buttons misalignment in the navbar Issue ! #735 & #777
  blog.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#815 Removed Unnecessary Load More Posts button From About Us Page
  about.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#818 fixed progress bar
  Scroll_and_progressbar.css
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#825 Updated README.md as per the requested changes
  README.md
  category.css
  category.html
  faq.png
  home.png
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#819 Redesign "Leave Comment" Section on Leading Blog Page
  blog.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#805 updated-contact-form
  contact_us.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#839 added about us page info
  about.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#846 Improved Blog Card, Supported for Light and Dark Theme
  index.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#845 fixed dark mode
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#867 Resolved issue: #842
  contact_us.html
  start_writing.css
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#869 Feat/GitHub icon twitter
  about.html
  blog.html
  category.html
  contact.html
  fashion.html
  food.html
  health.html
  index.html
  life.html
  start.html
  start_writing.html
  tech.html
  travel.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#877 Implemented the load posts functionality
  index.html
  script.js
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#881 Newsletter storing in database and a email is being sent to user
  backend/.env.example
  backend/Database.js
  backend/config/nodemailer.js
  backend/controllers/NewsLetterController.js
  backend/modal/NewsLetterModel.js
  backend/package-lock.json
  backend/package.json
  backend/server.js
  index.html
  main.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#889 feedback backend integrated with thank you mail support
  backend/config/nodemailer.js
  backend/controllers/ContactController.js
  backend/modal/ContactModel.js
  backend/server.js
  contact_us.html
  contact_us.js
  index.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#903 Added Animated Preloader : Issue no #836
  index.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#892 Improve alignment of start-voice button
  start_writing.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#890 added faq popup modal in all pages
  blog.html
  category.html
  start_writing.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#891 scroll to top button added on leading blog and start writing
  blog.html
  main.js
  start_writing.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#898 contact us issue solved : Contact us backend frontend working correctly #837 done
  backend/.env.example
  backend/server.js
  contact_us.css
  contact_us.html
  contact_us.js
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#922 UI/UX Enhancement for Login and Sign-Up Pages
  index.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#944 privacy policy page added fixes issue #662
  about.html
  blog.html
  category.html
  contact.html
  contact_us.html
  health.html
  index.html
  life.html
  privacy.html
  start.html
  start_writing.html
  tech.html
  travel.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#930 Collaborative writing
  start_writing.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#960 Navbar for mobile view
  about.html
  blog.html
  category.html
  contact_us.html
  google_signin.js
  index.html
  main.js
  start.html
  start_writing.html
  style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#967 Feat: Implement login and signup backend core logic using DB
  backend/model/User.js
  backend/package.json
  backend/server.js
  backend/signUp/signup.js
  login.html
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#987 Update Scrollup button #919
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#982 Update Footer design #920
  index.html
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#990 Feature/fixing about issue - (#948)
  about.html
  blog.html
  category.html
  contact.html
  fashion.html
  food.html
  health.html
  life.html
  privacy.html
  start.html
  start_writing.html
  tech.html
  travel.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#999 Create Comment and discussion Section
  blog.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1000 Solved Error `ReferenceError: cookieParser is not defined` in Backend
  backend/package-lock.json
  backend/package.json
  backend/server.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1014 Bug: Overflow-x direction
  blog-comment.js
  index.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1013 BUG: Edit faqs page text color
  blog-comment.js
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1023 Enhancing the visuals of the navbar "WordWise" Effects
  style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1024 Added form validation
  contact_us.js
  dist/contact_us.dev.js
  dist/contact_us.dev.js.map
  dist/contact_us.min.js
  dist/contact_us.min.js.map
Labels: gssoc-ext, level 1, hacktoberfest-accepted
